option(APP_USE_COMPILE_CACHE "" ON)

if (NOT DEFINED CMAKE_CXX_COMPILER_LAUNCHER)
    if (APP_USE_COMPILE_CACHE)
        message("Setting up compilation cache by using CCache")
        find_program(CCACHE_EXECUTABLE ccache)
        if (CCACHE_EXECUTABLE)
            set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_EXECUTABLE}" CACHE STRING "Compiler launcher path for C++")
            message("CCache found: ${CCACHE_EXECUTABLE}")
        else ()
            message("CCcache not found. Skipping using ccache")
        endif ()
    else ()
        message("Skipping using compilation cache")
    endif ()
else ()
    message("Using compiler launcher provided by user: ${CMAKE_CXX_COMPILER_LAUNCHER}")
endif ()