function(DisplayFunctionArguments PARAM1 PARAM2)
    message("All passed parameters: ${ARGV}")
    message("Extra parameters: ${ARGN}")
    message("All parameters count: ${ARGC}")
endfunction()

function(DisplayMacroArguments PARAM1)
    message("All passed parameters: ${ARGV}")
    message("Extra parameters: ${ARGN}")
    message("All parameters count: ${ARGC}")
endfunction()

function(DisplayForEachArgument PARAM1 PARAM2)
    foreach(ARG ${ARGV})
        message("Arg ${ARG}")
    endforeach()
endfunction()

function(DisplayOnlyExtra PARAM1 PARAM2)
    foreach(ARG IN LISTS ARGN)
        message("Arg ${ARG}")
    endforeach()
endfunction()

macro(MacroDisplayOnlyExtra PARAM1 PARAM2)
#    foreach(ARG IN LISTS ARGN)
    foreach(ARG ${ARGN})
        message("Arg ${ARG}")
    endforeach()
endmacro()

function(DisplayOnlyRequired PARAM1 PARAM2)
    list(LENGTH ${ARGN} EXTRA_COUNT)
    math(EXPR EXPECTED_COUNT "${ARGC} - ${EXTRA_COUNT} - 1")
    math(EXPR LAST_INDEX "${EXPECTED_COUNT} - 1")
    set(FIRST_INDEX 0)
    foreach(INDEX RANGE ${FIRST_INDEX} ${LAST_INDEX})
        message("Arg ${ARGV${INDEX}}")
    endforeach()
endfunction()

function(DisplayOnlyRequiredInObviousWay PARAM1 PARAM2)
    message("Arg ${PARAM1}")
    message("Arg ${PARAM2}")
endfunction()

function(DisplayFirstParam PARAM1)
    if (NOT DEFINED ARGV0)
        message("No extra params")
        return()
    endif()
    message("First extra param is: ${ARGV0}")
endfunction()

macro(MacroDisplayFirstParam PARAM1)
    if (DEFINED ARGV0)
        message("First extra param is: ${ARGV0}")
    else()
        message("No extra params")
    endif()
endmacro()